baseURL = 'http://127.0.0.1:8093/'
languageCode = 'en-us'
title = 'FOXON DOCS'


[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false


[params]

[params.footer]
    copyright = "All right reserved"
    version = true

[params.social]
    github = "https://github.com/Foxon-Consulting"


[params.docs]
    title = "Foxon Documentation"
    themeColor = "blue"
    darkMode = true

    sidebarIcons = true
    titleIcon = true